import { Surah, Language, Translation } from "./types";

export const SURAHS: Surah[] = [
  { id: 1, name: "الفاتحة", englishName: "Al-Fatihah", arabicName: "سُورَةُ ٱلْفَاتِحَةِ", revelationType: "Meccan", numberOfAyahs: 7, juz: 1 },
  { id: 2, name: "البقرة", englishName: "Al-Baqarah", arabicName: "سُورَةُ ٱلْبَقَرَةِ", revelationType: "Medinan", numberOfAyahs: 286, juz: 1 },
  { id: 3, name: "آل عمران", englishName: "Ali 'Imran", arabicName: "سُورَةُ آلِ عِمْرَانَ", revelationType: "Medinan", numberOfAyahs: 200, juz: 3 },
  { id: 4, name: "النساء", englishName: "An-Nisa", arabicName: "سُورَةُ ٱلنِّسَاءِ", revelationType: "Medinan", numberOfAyahs: 176, juz: 4 },
  { id: 5, name: "المائدة", englishName: "Al-Ma'idah", arabicName: "سُورَةُ ٱلْمَائِدَةِ", revelationType: "Medinan", numberOfAyahs: 120, juz: 6 },
  { id: 6, name: "الأنعام", englishName: "Al-An'am", arabicName: "سُورَةُ ٱلْأَنْعَامِ", revelationType: "Meccan", numberOfAyahs: 165, juz: 7 },
  { id: 7, name: "الأعراف", englishName: "Al-A'raf", arabicName: "سُورَةُ ٱلْأَعْرَافِ", revelationType: "Meccan", numberOfAyahs: 206, juz: 8 },
  { id: 8, name: "الأنفال", englishName: "Al-Anfal", arabicName: "سُورَةُ ٱلْأَنْفَالِ", revelationType: "Medinan", numberOfAyahs: 75, juz: 9 },
  { id: 9, name: "التوبة", englishName: "At-Tawbah", arabicName: "سُورَةُ ٱلتَّوْبَةِ", revelationType: "Medinan", numberOfAyahs: 129, juz: 10 },
  { id: 10, name: "يونس", englishName: "Yunus", arabicName: "سُورَةُ يُونُسَ", revelationType: "Meccan", numberOfAyahs: 109, juz: 11 },
  { id: 11, name: "هود", englishName: "Hud", arabicName: "سُورَةُ هُودٍ", revelationType: "Meccan", numberOfAyahs: 123, juz: 11 },
  { id: 12, name: "يوسف", englishName: "Yusuf", arabicName: "سُورَةُ يُوسُفَ", revelationType: "Meccan", numberOfAyahs: 111, juz: 12 },
  { id: 13, name: "الرعد", englishName: "Ar-Ra'd", arabicName: "سُورَةُ ٱلرَّعْدِ", revelationType: "Medinan", numberOfAyahs: 43, juz: 13 },
  { id: 14, name: "إبراهيم", englishName: "Ibrahim", arabicName: "سُورَةُ إِبْرَاهِيمَ", revelationType: "Meccan", numberOfAyahs: 52, juz: 13 },
  { id: 15, name: "الحجر", englishName: "Al-Hijr", arabicName: "سُورَةُ ٱلْحِجْرِ", revelationType: "Meccan", numberOfAyahs: 99, juz: 14 },
  { id: 16, name: "النحل", englishName: "An-Nahl", arabicName: "سُورَةُ ٱلنَّحْلِ", revelationType: "Meccan", numberOfAyahs: 128, juz: 14 },
  { id: 17, name: "الإسراء", englishName: "Al-Isra", arabicName: "سُورَةُ ٱلْإِسْرَاءِ", revelationType: "Meccan", numberOfAyahs: 111, juz: 15 },
  { id: 18, name: "الكهف", englishName: "Al-Kahf", arabicName: "سُورَةُ ٱلْكَهْفِ", revelationType: "Meccan", numberOfAyahs: 110, juz: 15 },
  { id: 19, name: "مريم", englishName: "Maryam", arabicName: "سُورَةُ مَرْيَمَ", revelationType: "Meccan", numberOfAyahs: 98, juz: 16 },
  { id: 20, name: "طه", englishName: "Ta-Ha", arabicName: "سُورَةُ طه", revelationType: "Meccan", numberOfAyahs: 135, juz: 16 },
  { id: 21, name: "الأنبياء", englishName: "Al-Anbiya", arabicName: "سُورَةُ ٱلْأَنْبِيَاءِ", revelationType: "Meccan", numberOfAyahs: 112, juz: 17 },
  { id: 22, name: "الحج", englishName: "Al-Hajj", arabicName: "سُورَةُ ٱلْحَجِّ", revelationType: "Medinan", numberOfAyahs: 78, juz: 17 },
  { id: 23, name: "المؤمنون", englishName: "Al-Mu'minun", arabicName: "سُورَةُ ٱلْمُؤْمِنُونَ", revelationType: "Meccan", numberOfAyahs: 118, juz: 18 },
  { id: 24, name: "النور", englishName: "An-Nur", arabicName: "سُورَةُ ٱلنُّورِ", revelationType: "Medinan", numberOfAyahs: 64, juz: 18 },
  { id: 25, name: "الفرقان", englishName: "Al-Furqan", arabicName: "سُورَةُ ٱلْفُرْقَانِ", revelationType: "Meccan", numberOfAyahs: 77, juz: 18 },
  { id: 26, name: "الشعراء", englishName: "Ash-Shu'ara", arabicName: "سُورَةُ ٱلشُّعَرَاءِ", revelationType: "Meccan", numberOfAyahs: 227, juz: 19 },
  { id: 27, name: "النمل", englishName: "An-Naml", arabicName: "سُورَةُ ٱلنَّمْلِ", revelationType: "Meccan", numberOfAyahs: 93, juz: 19 },
  { id: 28, name: "القصص", englishName: "Al-Qasas", arabicName: "سُورَةُ ٱلْقصَصِ", revelationType: "Meccan", numberOfAyahs: 88, juz: 20 },
  { id: 29, name: "العنكبوت", englishName: "Al-'Ankabut", arabicName: "سُورَةُ ٱلْعَنْكَبُوتِ", revelationType: "Meccan", numberOfAyahs: 69, juz: 20 },
  { id: 30, name: "الروم", englishName: "Ar-Rum", arabicName: "سُورَةُ ٱلرُّومِ", revelationType: "Meccan", numberOfAyahs: 60, juz: 21 },
  { id: 31, name: "لقمان", englishName: "Luqman", arabicName: "سُورَةُ لُقْمَانَ", revelationType: "Meccan", numberOfAyahs: 34, juz: 21 },
  { id: 32, name: "السجدة", englishName: "As-Sajdah", arabicName: "سُورَةُ ٱلسَّجْدَةِ", revelationType: "Meccan", numberOfAyahs: 30, juz: 21 },
  { id: 33, name: "الأحزاب", englishName: "Al-Ahzab", arabicName: "سُورَةُ ٱلْأَحْزَابِ", revelationType: "Medinan", numberOfAyahs: 73, juz: 21 },
  { id: 34, name: "سبأ", englishName: "Saba", arabicName: "سُورَةُ سَبَإٍ", revelationType: "Meccan", numberOfAyahs: 54, juz: 22 },
  { id: 35, name: "فاطر", englishName: "Fatir", arabicName: "سُورَةُ فَاطِرٍ", revelationType: "Meccan", numberOfAyahs: 45, juz: 22 },
  { id: 36, name: "يس", englishName: "Ya-Sin", arabicName: "سُورَةُ يس", revelationType: "Meccan", numberOfAyahs: 83, juz: 22 },
  { id: 37, name: "الصافات", englishName: "As-Saffat", arabicName: "سُورَةُ ٱلصَّافَّاتِ", revelationType: "Meccan", numberOfAyahs: 182, juz: 23 },
  { id: 38, name: "ص", englishName: "Sad", arabicName: "سُورَةُ ص", revelationType: "Meccan", numberOfAyahs: 88, juz: 23 },
  { id: 39, name: "الزمر", englishName: "Az-Zumar", arabicName: "سُورَةُ ٱلزُّمَرِ", revelationType: "Meccan", numberOfAyahs: 75, juz: 23 },
  { id: 40, name: "غافر", englishName: "Ghafir", arabicName: "سُورَةُ غَافِرٍ", revelationType: "Meccan", numberOfAyahs: 85, juz: 24 },
  { id: 41, name: "فصلت", englishName: "Fussilat", arabicName: "سُورَةُ فُصِّلَتْ", revelationType: "Meccan", numberOfAyahs: 54, juz: 24 },
  { id: 42, name: "الشورى", englishName: "Ash-Shura", arabicName: "سُورَةُ ٱلشُّورَىٰ", revelationType: "Meccan", numberOfAyahs: 53, juz: 25 },
  { id: 43, name: "الزخرف", englishName: "Az-Zukhruf", arabicName: "سُورَةُ ٱلزُّخْرُفِ", revelationType: "Meccan", numberOfAyahs: 89, juz: 25 },
  { id: 44, name: "الدخان", englishName: "Ad-Dukhan", arabicName: "سُورَةُ ٱلدُّخَانِ", revelationType: "Meccan", numberOfAyahs: 59, juz: 25 },
  { id: 45, name: "الجاثية", englishName: "Al-Jathiyah", arabicName: "سُورَةُ ٱلْجَاثِيَةِ", revelationType: "Meccan", numberOfAyahs: 37, juz: 25 },
  { id: 46, name: "الأحقاف", englishName: "Al-Ahqaf", arabicName: "سُورَةُ ٱلْأَحْقَافِ", revelationType: "Meccan", numberOfAyahs: 35, juz: 26 },
  { id: 47, name: "محمد", englishName: "Muhammad", arabicName: "سُورَةُ مُحَمَّدٍ", revelationType: "Medinan", numberOfAyahs: 38, juz: 26 },
  { id: 48, name: "الفتح", englishName: "Al-Fath", arabicName: "سُورَةُ ٱلْفَتْحِ", revelationType: "Medinan", numberOfAyahs: 29, juz: 26 },
  { id: 49, name: "الحجرات", englishName: "Al-Hujurat", arabicName: "سُورَةُ ٱلْحُجُرَاتِ", revelationType: "Medinan", numberOfAyahs: 18, juz: 26 },
  { id: 50, name: "ق", englishName: "Qaf", arabicName: "سُورَةُ ق", revelationType: "Meccan", numberOfAyahs: 45, juz: 26 },
  { id: 51, name: "الذاريات", englishName: "Adh-Dhariyat", arabicName: "سُورَةُ ٱذَّارِيَاتِ", revelationType: "Meccan", numberOfAyahs: 60, juz: 26 },
  { id: 52, name: "الطور", englishName: "At-Tur", arabicName: "سُورَةُ ٱلطُّورِ", revelationType: "Meccan", numberOfAyahs: 49, juz: 27 },
  { id: 53, name: "النجم", englishName: "An-Najm", arabicName: "سُورَةُ ٱلنَّجْمِ", revelationType: "Meccan", numberOfAyahs: 62, juz: 27 },
  { id: 54, name: "القمر", englishName: "Al-Qamar", arabicName: "سُورَةُ ٱلْقَمَرِ", revelationType: "Meccan", numberOfAyahs: 55, juz: 27 },
  { id: 55, name: "الرحمن", englishName: "Ar-Rahman", arabicName: "سُورَةُ ٱلرَّحْمَٰنِ", revelationType: "Medinan", numberOfAyahs: 78, juz: 27 },
  { id: 56, name: "الواقعة", englishName: "Al-Waqi'ah", arabicName: "سُورَةُ ٱلْوَاقِعَةِ", revelationType: "Meccan", numberOfAyahs: 96, juz: 27 },
  { id: 57, name: "الحديد", englishName: "Al-Hadid", arabicName: "سُورَةُ ٱلْحَدِيدِ", revelationType: "Medinan", numberOfAyahs: 29, juz: 27 },
  { id: 58, name: "المجادلة", englishName: "Al-Mujadilah", arabicName: "سُورَةُ ٱلْمُجَادَلَةِ", revelationType: "Medinan", numberOfAyahs: 22, juz: 28 },
  { id: 59, name: "الحشر", englishName: "Al-Hashr", arabicName: "سُورَةُ ٱلْحَشْرِ", revelationType: "Medinan", numberOfAyahs: 24, juz: 28 },
  { id: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", arabicName: "سُورَةُ ٱلْمُمْتَحَنَةِ", revelationType: "Medinan", numberOfAyahs: 13, juz: 28 },
  { id: 61, name: "الصف", englishName: "As-Saff", arabicName: "سُورَةُ ٱلصَّافِّ", revelationType: "Medinan", numberOfAyahs: 14, juz: 28 },
  { id: 62, name: "الجمعة", englishName: "Al-Jumu'ah", arabicName: "سُورَةُ ٱلْجُمُعَةِ", revelationType: "Medinan", numberOfAyahs: 11, juz: 28 },
  { id: 63, name: "المنافقون", englishName: "Al-Munafiqun", arabicName: "سُورَةُ ٱلْمُنَافِقُونَ", revelationType: "Medinan", numberOfAyahs: 11, juz: 28 },
  { id: 64, name: "التغابن", englishName: "At-Taghabun", arabicName: "سُورَةُ ٱلتَّغَابُنِ", revelationType: "Medinan", numberOfAyahs: 18, juz: 28 },
  { id: 65, name: "الطلاق", englishName: "At-Talaq", arabicName: "سُورَةُ ٱلطَّلَاقِ", revelationType: "Medinan", numberOfAyahs: 12, juz: 28 },
  { id: 66, name: "التحريم", englishName: "At-Tahrim", arabicName: "سُورَةُ ٱلتَّحْرِيمِ", revelationType: "Medinan", numberOfAyahs: 12, juz: 28 },
  { id: 67, name: "الملك", englishName: "Al-Mulk", arabicName: "سُورَةُ ٱلْمُلْكِ", revelationType: "Meccan", numberOfAyahs: 30, juz: 29 },
  { id: 68, name: "القلم", englishName: "Al-Qalam", arabicName: "سُورَةُ ٱلْقَلَمِ", revelationType: "Meccan", numberOfAyahs: 52, juz: 29 },
  { id: 69, name: "الحاقة", englishName: "Al-Haqqah", arabicName: "سُورَةُ ٱلْحَاقَّةِ", revelationType: "Meccan", numberOfAyahs: 52, juz: 29 },
  { id: 70, name: "المعارج", englishName: "Al-Ma'arij", arabicName: "سُورَةُ ٱلْمَعَارِجِ", revelationType: "Meccan", numberOfAyahs: 44, juz: 29 },
  { id: 71, name: "نوح", englishName: "Nuh", arabicName: "سُورَةُ نُوحٍ", revelationType: "Meccan", numberOfAyahs: 28, juz: 29 },
  { id: 72, name: "الجن", englishName: "Al-Jinn", arabicName: "سُورَةُ ٱلْجِنِّ", revelationType: "Meccan", numberOfAyahs: 28, juz: 29 },
  { id: 73, name: "المزمل", englishName: "Al-Muzzammil", arabicName: "سُورَةُ ٱلْمُزَّمِّلِ", revelationType: "Meccan", numberOfAyahs: 20, juz: 29 },
  { id: 74, name: "المدثر", englishName: "Al-Muddaththir", arabicName: "سُورَةُ ٱلْمُدَّثِّرِ", revelationType: "Meccan", numberOfAyahs: 56, juz: 29 },
  { id: 75, name: "القيامة", englishName: "Al-Qiyamah", arabicName: "سُورَةُ ٱلْقِيَامَةِ", revelationType: "Meccan", numberOfAyahs: 40, juz: 29 },
  { id: 76, name: "الإنسان", englishName: "Al-Insan", arabicName: "سُورَةُ ٱلْإِنسَانِ", revelationType: "Medinan", numberOfAyahs: 31, juz: 29 },
  { id: 77, name: "المرسلات", englishName: "Al-Mursalat", arabicName: "سُورَةُ ٱلْمُرْسَلَاتِ", revelationType: "Meccan", numberOfAyahs: 50, juz: 29 },
  { id: 78, name: "النبأ", englishName: "An-Naba", arabicName: "سُورَةُ ٱلنَّبَإِ", revelationType: "Meccan", numberOfAyahs: 40, juz: 30 },
  { id: 79, name: "النازعات", englishName: "An-Nazi'at", arabicName: "سُورَةُ ٱلنَّازِعَاتِ", revelationType: "Meccan", numberOfAyahs: 46, juz: 30 },
  { id: 80, name: "عبس", englishName: "'Abasa", arabicName: "سُورَةُ عَبَسَ", revelationType: "Meccan", numberOfAyahs: 42, juz: 30 },
  { id: 81, name: "التكوير", englishName: "At-Takwir", arabicName: "سُورَةُ ٱلتَّكْوِيرِ", revelationType: "Meccan", numberOfAyahs: 29, juz: 30 },
  { id: 82, name: "الانفطار", englishName: "Al-Infitar", arabicName: "سُورَةُ ٱلْإِنفِطَارِ", revelationType: "Meccan", numberOfAyahs: 19, juz: 30 },
  { id: 83, name: "المطففين", englishName: "Al-Mutaffifin", arabicName: "سُورَةُ ٱلْمُطَفِّفِينَ", revelationType: "Meccan", numberOfAyahs: 36, juz: 30 },
  { id: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", arabicName: "سُورَةُ ٱلِانشِقَاقِ", revelationType: "Meccan", numberOfAyahs: 25, juz: 30 },
  { id: 85, name: "البروج", englishName: "Al-Buruj", arabicName: "سُورَةُ ٱلْبُرُوجِ", revelationType: "Meccan", numberOfAyahs: 22, juz: 30 },
  { id: 86, name: "الطارق", englishName: "At-Tariq", arabicName: "سُورَةُ ٱلطَّارِقِ", revelationType: "Meccan", numberOfAyahs: 17, juz: 30 },
  { id: 87, name: "الأعلى", englishName: "Al-A'la", arabicName: "سُورَةُ ٱلْأَعْلَىٰ", revelationType: "Meccan", numberOfAyahs: 19, juz: 30 },
  { id: 88, name: "الغاشية", englishName: "Al-Ghashiyah", arabicName: "سُورَةُ ٱلْغَاشِيَةِ", revelationType: "Meccan", numberOfAyahs: 26, juz: 30 },
  { id: 89, name: "الفجر", englishName: "Al-Fajr", arabicName: "سُورَةُ ٱلْفَجْرِ", revelationType: "Meccan", numberOfAyahs: 30, juz: 30 },
  { id: 90, name: "البلد", englishName: "Al-Balad", arabicName: "سُورَةُ ٱلْبَلَدِ", revelationType: "Meccan", numberOfAyahs: 20, juz: 30 },
  { id: 91, name: "الشمس", englishName: "Ash-Shams", arabicName: "سُورَةُ ٱلشَّمْسِ", revelationType: "Meccan", numberOfAyahs: 15, juz: 30 },
  { id: 92, name: "الليل", englishName: "Al-Layl", arabicName: "سُورَةُ ٱللَّيْلِ", revelationType: "Meccan", numberOfAyahs: 21, juz: 30 },
  { id: 93, name: "الضحى", englishName: "Ad-Duha", arabicName: "سُورَةُ ٱلضُّحَىٰ", revelationType: "Meccan", numberOfAyahs: 11, juz: 30 },
  { id: 94, name: "الشرح", englishName: "Ash-Sharh", arabicName: "سُورَةُ ٱلشَّرْحِ", revelationType: "Meccan", numberOfAyahs: 8, juz: 30 },
  { id: 95, name: "التين", englishName: "At-Tin", arabicName: "سُورَةُ ٱلتِّينِ", revelationType: "Meccan", numberOfAyahs: 8, juz: 30 },
  { id: 96, name: "العلق", englishName: "Al-'Alaq", arabicName: "سُورَةُ ٱلْعَلَقِ", revelationType: "Meccan", numberOfAyahs: 19, juz: 30 },
  { id: 97, name: "القدر", englishName: "Al-Qadr", arabicName: "سُورَةُ ٱلْقَدْرِ", revelationType: "Meccan", numberOfAyahs: 5, juz: 30 },
  { id: 98, name: "البينة", englishName: "Al-Bayyinah", arabicName: "سُورَةُ ٱلْبَيِّنَةِ", revelationType: "Medinan", numberOfAyahs: 8, juz: 30 },
  { id: 99, name: "الزلزلة", englishName: "Az-Zalzalah", arabicName: "سُورَةُ ٱلزَّلْزَلَةِ", revelationType: "Medinan", numberOfAyahs: 8, juz: 30 },
  { id: 100, name: "العاديات", englishName: "Al-'Adiyat", arabicName: "سُورَةُ ٱلْعَادِيَاتِ", revelationType: "Meccan", numberOfAyahs: 11, juz: 30 },
  { id: 101, name: "القارعة", englishName: "Al-Qari'ah", arabicName: "سُورَةُ ٱلْقَارِعَةِ", revelationType: "Meccan", numberOfAyahs: 11, juz: 30 },
  { id: 102, name: "التكاثر", englishName: "At-Takathur", arabicName: "سُورَةُ ٱلتَّكاثُرِ", revelationType: "Meccan", numberOfAyahs: 8, juz: 30 },
  { id: 103, name: "العصر", englishName: "Al-'Asr", arabicName: "سُورَةُ ٱلْعَصْرِ", revelationType: "Meccan", numberOfAyahs: 3, juz: 30 },
  { id: 104, name: "الهمزة", englishName: "Al-Humazah", arabicName: "سُورَةُ ٱلْهُمَزَةِ", revelationType: "Meccan", numberOfAyahs: 9, juz: 30 },
  { id: 105, name: "الفيل", englishName: "Al-Fil", arabicName: "سُورَةُ ٱلْفِيلِ", revelationType: "Meccan", numberOfAyahs: 5, juz: 30 },
  { id: 106, name: "قريش", englishName: "Quraysh", arabicName: "سُورَةُ قُرَيْشٍ", revelationType: "Meccan", numberOfAyahs: 4, juz: 30 },
  { id: 107, name: "الماعون", englishName: "Al-Ma'un", arabicName: "سُورَةُ ٱلْمَاعُونَ", revelationType: "Meccan", numberOfAyahs: 7, juz: 30 },
  { id: 108, name: "الكوثر", englishName: "Al-Kawthar", arabicName: "سُورَةُ ٱلْكَوْثَرِ", revelationType: "Meccan", numberOfAyahs: 3, juz: 30 },
  { id: 109, name: "الكافرون", englishName: "Al-Kafirun", arabicName: "سُورَةُ ٱلْكَافِرُونَ", revelationType: "Meccan", numberOfAyahs: 6, juz: 30 },
  { id: 110, name: "النصر", englishName: "An-Nasr", arabicName: "سُورَةُ ٱلنَّصْرِ", revelationType: "Medinan", numberOfAyahs: 3, juz: 30 },
  { id: 111, name: "المسد", englishName: "Al-Masad", arabicName: "سُورَةُ ٱلْمَسَدِ", revelationType: "Meccan", numberOfAyahs: 5, juz: 30 },
  { id: 112, name: "الإخلاص", englishName: "Al-Ikhlas", arabicName: "سُورَةُ ٱلْإِخْلَاصِ", revelationType: "Meccan", numberOfAyahs: 4, juz: 30 },
  { id: 113, name: "الفلق", englishName: "Al-Falaq", arabicName: "سُورَةُ ٱلْفَلَقِ", revelationType: "Meccan", numberOfAyahs: 5, juz: 30 },
  { id: 114, name: "الناس", englishName: "An-Nas", arabicName: "سُورَةُ ٱلنَّاسِ", revelationType: "Meccan", numberOfAyahs: 6, juz: 30 },
];

export const EXTERNAL_LINKS = {
  QURAN_READ: "https://quran-elkareem.netlify.app",
  QURAN_RADIO: "https://stream.radiojar.com/8s5u5tpdtwzuv"
};

export const TRANSLATIONS: Record<Language, Translation> = {
  ar: {
    title: "أهل القرآن الكريم",
    subtitle: "بأصوات كبار القراء",
    searchPlaceholder: "ابحث عن قارئ...",
    recitersCount: "قارئ",
    availableSurahs: "سورة متاحة",
    settings: "الإعدادات",
    language: "اللغة",
    mode: "الوضع",
    night: "ليلي",
    version: "الإصدار",
    charity: "صدقة جارية لأمي رحمها الله وجميع موتى المسلمين .",
    madeBy: "تم بواسطة كريم آل عشماوي",
    readAndMemorize: "حفظ القرآن",
    cairoRadio: "الإذاعة",
    meccan: "مكية",
    medinan: "مدنية",
    ayahs: "آية",
    wakeLock: "تعليق الشاشة",
    wakeLockActive: "الشاشة معلقة",
    close: "إغلاق",
    selectReciter: "اختر القارئ",
    welcome: "مرحباً بك في استوديو القرآن",
    welcomeDesc: "اختر قارئك المفضل من القائمة الجانبية وابدأ الاستماع إلى آيات الذكر الحكيم",
    home: "الرئيسية",
    stop: "إيقاف التشغيل",
    repeat: "تكرار",
    playbackSpeed: "سرعة القراءة",
    juz: "الجزء",
    copyLink: "نسخ الرابط",
    linkCopied: "تم النسخ!"
  },
  en: {
    title: "Quran Studio",
    subtitle: "With Great Reciters",
    searchPlaceholder: "Search for a reciter...",
    recitersCount: "Reciters",
    availableSurahs: "Surahs available",
    settings: "Settings",
    language: "Language",
    mode: "Mode",
    night: "Night",
    version: "Version",
    charity: "Ongoing charity for my mother, may God have mercy on her",
    madeBy: "Made by Karim Al Ashmawi",
    readAndMemorize: "Read & Memorize",
    cairoRadio: "Cairo Radio",
    meccan: "Meccan",
    medinan: "Medinan",
    ayahs: "Ayahs",
    wakeLock: "Wake Lock",
    wakeLockActive: "Screen Active",
    close: "Close",
    selectReciter: "Select Reciter",
    welcome: "Welcome to Quran Studio",
    welcomeDesc: "Select your favorite reciter from the side menu and start listening to the Holy Quran",
    home: "Home",
    stop: "Stop Playback",
    repeat: "Repeat",
    playbackSpeed: "Playback Speed",
    juz: "Juz",
    copyLink: "Copy Link",
    linkCopied: "Copied!"
  },
  tr: {
    title: "Kuran Stüdyosu",
    subtitle: "Büyük Hafızlarla",
    searchPlaceholder: "Hafız ara...",
    recitersCount: "Hafızlar",
    availableSurahs: "Mevcut Sureler",
    settings: "Ayarlar",
    language: "Dil",
    mode: "Mod",
    night: "Gece",
    version: "Versiyon",
    charity: "Annem için sadaka-i cariye, Allah ona rahmet etsin",
    madeBy: "Karim Al Ashmawi tarafından yapıldı",
    readAndMemorize: "Oku ve Ezberle",
    cairoRadio: "Kahire Radyosu",
    meccan: "Mekki",
    medinan: "Medeni",
    ayahs: "Ayetler",
    wakeLock: "Ekranı Açık Tut",
    wakeLockActive: "Ekran Aktif",
    close: "Kapat",
    selectReciter: "Hafız Seç",
    welcome: "Kuran Stüdyosuna Hoş Geldiniz",
    welcomeDesc: "Yan menüden favori hafızınızı seçin ve Kuran-ı Kerim'i dinlemeye başlayın",
    home: "Ana Sayfa",
    stop: "Oynatmayı Durdur",
    repeat: "Tekrarla",
    playbackSpeed: "Oynatma Hızı",
    juz: "Cüz",
    copyLink: "Bağlantıyı Kopyala",
    linkCopied: "Kopyalandı!"
  }
};
